Sync dotfiles

diff --git a/.config/zsh-custom/func b/.config/zsh-custom/func
--- a/.config/zsh-custom/func
+++ b/.config/zsh-custom/func
@@ -13,13 +13,13 @@ addToPathFront() {
 }
 
 venv() {
-    if ! command -v python3 >/dev/null 2>&1 && ! command -v python >/dev/null 2>&1; then
-        echo "Python not found."
+    if ! command -v uv >/dev/null 2>&1; then
+        echo "uv not found."
         return
     fi
 
     if [[ ! -f .venv/bin/activate && ! -f .venv/Scripts/activate ]]; then
-        python3 -m venv .venv || python -m venv .venv
+        uv venv
         echo "Virtual environment created."
     fi
 
